# Generated by Django 5.0.6 on 2024-05-26 06:37

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import Board.schema


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Organization", "0002_welfareorganization_delete_welfare_organization"),
        ("Users", "0005_footprint_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "board_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="看板編號"
                    ),
                ),
                ("topic", models.CharField(max_length=100, verbose_name="標題")),
                (
                    "content",
                    models.CharField(max_length=100000, null=True, verbose_name="內容"),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "type",
                    enumfields.fields.EnumField(
                        default="government", enum=Board.schema.BoardType, max_length=10
                    ),
                ),
                (
                    "fb_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Organization.food_bank",
                        verbose_name="食物銀行",
                    ),
                ),
                (
                    "leftover_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.leftover",
                        verbose_name="剩食編號",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.user",
                        verbose_name="使用者編號",
                    ),
                ),
                (
                    "waste_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.waste",
                        verbose_name="二手物品編號",
                    ),
                ),
                (
                    "wo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Organization.welfareorganization",
                        verbose_name="社福機構",
                    ),
                ),
            ],
        ),
    ]
