# Generated by Django 5.0.6 on 2024-05-28 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Board", "0009_alter_board_user_id"),
        ("Organization", "0002_welfareorganization_delete_welfare_organization"),
        ("Users", "0007_alter_user_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="fb_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Organization.food_bank",
                verbose_name="食物銀行",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="leftover_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.leftover",
                verbose_name="剩食編號",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="waste_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.waste",
                verbose_name="二手物品編號",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="wo_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Organization.welfareorganization",
                verbose_name="社福機構",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="user_id",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="使用者編號",
            ),
        ),
    ]
