# Generated by Django 5.0.6 on 2024-05-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Users", "0005_footprint_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("contribution", models.CharField(max_length=10000)),
                ("total_carbon_footprint", models.CharField(max_length=10000)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.user",
                    ),
                ),
            ],
        ),
    ]
