# Generated by Django 5.0.6 on 2024-05-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food_Bank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("county", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Welfare_Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("county", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
    ]
