# Generated by Django 5.0.6 on 2024-05-26 05:50

import enumfields.fields
from django.db import migrations, models

import Organization.schema


class Migration(migrations.Migration):
    dependencies = [
        ("Organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelfareOrganization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("county", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=20)),
                (
                    "type",
                    enumfields.fields.EnumField(
                        default="government",
                        enum=Organization.schema.OrganizationType,
                        help_text="所屬類型",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Welfare_Organization",
        ),
    ]
