# Generated by Django 5.0.6 on 2024-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Organization", "0002_welfareorganization_delete_welfare_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="welfareorganization",
            name="address",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
