# Generated by Django 5.0.6 on 2024-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Organization", "0003_welfareorganization_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_bank",
            name="district",
            field=models.CharField(default=" ", max_length=20),
        ),
    ]
