# Generated by Django 5.0.6 on 2024-05-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("users_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.FloatField()),
                ("location", models.CharField(max_length=10)),
            ],
        ),
    ]
