# Generated by Django 5.0.6 on 2024-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0002_rename_users_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leftover",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=20)),
                ("provider", models.CharField(max_length=10)),
                ("date_put_in", models.DateTimeField(auto_now_add=True)),
                ("label", models.DateTimeField(max_length=20)),
                ("portion", models.CharField(max_length=20)),
                ("sent_to", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Waste",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=20)),
                ("provider", models.CharField(max_length=10)),
                ("date_put_in", models.DateTimeField(auto_now_add=True)),
                ("label", models.DateTimeField(max_length=20)),
                ("sent_to", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="author",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
