# Generated by Django 5.0.6 on 2024-05-21 20:15

import django.core.validators
import enumfields.fields
from django.db import migrations, models

import Users.schema


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0003_leftover_waste_remove_user_author_alter_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        default=0.0,
                        help_text="移動距離(km)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "method",
                    enumfields.fields.EnumField(
                        default="mrt",
                        enum=Users.schema.CommuteMethod,
                        help_text="通勤交通方式",
                        max_length=10,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="活動時間"),
                ),
                (
                    "carbon_footprint",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name="累計碳足跡",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="leftover",
            name="portion",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
