# Generated by Django 5.0.6 on 2024-05-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0004_footprint_alter_leftover_portion"),
    ]

    operations = [
        migrations.AddField(
            model_name="footprint",
            name="user_id",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="Users.user"
            ),
        ),
    ]
