# Generated by Django 5.0.6 on 2024-05-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0006_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
    ]
