# Generated by Django 5.0.6 on 2024-05-28 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0007_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footprint",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
