# Generated by Django 5.0.6 on 2024-06-11 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Organization", "0004_food_bank_district"),
        ("Users", "0008_alter_footprint_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leftover",
            name="label",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="leftover",
            name="portion",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="leftover",
            name="sent_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Organization.food_bank",
            ),
        ),
        migrations.AlterField(
            model_name="waste",
            name="label",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="waste",
            name="sent_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Organization.welfareorganization",
            ),
        ),
    ]
