# Generated by Django 5.0.6 on 2024-06-11 13:03

import enumfields.fields
from django.db import migrations, models

import Users.schema


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0010_foodtable_alter_leftover_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footprint",
            old_name="user_id",
            new_name="users_id",
        ),
        migrations.AlterField(
            model_name="footprint",
            name="date",
            field=models.DateTimeField(verbose_name="活動時間"),
        ),
        migrations.AlterField(
            model_name="footprint",
            name="method",
            field=enumfields.fields.EnumField(
                default="car",
                enum=Users.schema.CommuteMethod,
                help_text="通勤交通方式",
                max_length=20,
            ),
        ),
    ]
