# Generated by Django 5.0.6 on 2024-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0013_alter_leftover_portion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leftover",
            name="label",
        ),
        migrations.RemoveField(
            model_name="waste",
            name="label",
        ),
        migrations.AlterField(
            model_name="leftover",
            name="date_put_in",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
