# Generated by Django 5.0.6 on 2024-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0014_remove_leftover_label_remove_waste_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footprint",
            name="date",
            field=models.DateField(verbose_name="活動時間"),
        ),
        migrations.AlterField(
            model_name="leftover",
            name="date_put_in",
            field=models.DateField(auto_now_add=True),
        ),
    ]
